-- MySQL Script generated by MySQL Workbench
-- mié 24 nov 2021 11:48:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_pizzeria` ;

-- -----------------------------------------------------
-- Table `db_pizzeria`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`ciudad` (
  `id_ciudad` INT NOT NULL,
  `nom_ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`cliente` (
  `rut_clie` VARCHAR(9) NOT NULL,
  `nom_clie` VARCHAR(200) NOT NULL,
  `ape_clie` VARCHAR(200) NOT NULL,
  `tel_clie` INT NOT NULL,
  `dir_clie` VARCHAR(200) NOT NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`rut_clie`),
  INDEX `fk_cliente_ciudad1_idx` (`id_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_ciudad1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `db_pizzeria`.`ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`tipo` (
  `id_tipo` INT NOT NULL,
  `nom_tipo` VARCHAR(200) NOT NULL,
  `capacidad_tipo` INT NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`vehiculo` (
  `id_veh` INT NOT NULL,
  `patente` VARCHAR(10) NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id_veh`),
  INDEX `fk_vehiculo_tipo1_idx` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db_pizzeria`.`tipo` (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`repartidor` (
  `rut_rep` VARCHAR(9) NOT NULL,
  `nom_rep` VARCHAR(200) NOT NULL,
  `ape_rep` VARCHAR(200) NOT NULL,
  `tel_rep` INT NOT NULL,
  `id_veh` INT NOT NULL,
  PRIMARY KEY (`rut_rep`),
  INDEX `fk_repartidor_vehiculo1_idx` (`id_veh` ASC) VISIBLE,
  CONSTRAINT `fk_repartidor_vehiculo1`
    FOREIGN KEY (`id_veh`)
    REFERENCES `db_pizzeria`.`vehiculo` (`id_veh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`pedido` (
  `id_pedido` INT NOT NULL,
  `total_pedido` INT NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `fecha_reparto` DATETIME NULL,
  `rut_clie` VARCHAR(9) NOT NULL,
  `rut_rep` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_repartidor1_idx` (`rut_rep` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`rut_clie` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_repartidor1`
    FOREIGN KEY (`rut_rep`)
    REFERENCES `db_pizzeria`.`repartidor` (`rut_rep`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`rut_clie`)
    REFERENCES `db_pizzeria`.`cliente` (`rut_clie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`tamano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`tamano` (
  `id_tam` INT NOT NULL,
  `nom_tam` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_tam`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`pizza` (
  `id_piz` INT NOT NULL,
  `nom_piz` VARCHAR(200) NOT NULL,
  `precio_piz` INT NOT NULL,
  `id_tam` INT NOT NULL,
  PRIMARY KEY (`id_piz`),
  INDEX `fk_pizza_tamano1_idx` (`id_tam` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_tamano1`
    FOREIGN KEY (`id_tam`)
    REFERENCES `db_pizzeria`.`tamano` (`id_tam`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_pizzeria`.`pedido_has_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzeria`.`pedido_has_pizza` (
  `id_pedido` INT NOT NULL,
  `id_piz` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_piz` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_piz`),
  INDEX `fk_pedido_has_pizza_pizza1_idx` (`id_piz` ASC) VISIBLE,
  INDEX `fk_pedido_has_pizza_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_pizza_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `db_pizzeria`.`pedido` (`id_pedido`),
  CONSTRAINT `fk_pedido_has_pizza_pizza1`
    FOREIGN KEY (`id_piz`)
    REFERENCES `db_pizzeria`.`pizza` (`id_piz`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

